#include "../tools.h"

char* get_icon_by_id(int id){
    switch(id){
        case MARKER:
            return (char*)":images/marker.svg";
        case PEN:
            return (char*)":images/pen.svg";
        case ERASER:
            return (char*)":images/eraser.svg";
        case CIRCLE:
            return (char*)":images/circle.svg";
        case SPLINE:
            return (char*)":images/spline.svg";
        case LINE:
            return (char*)":images/line.svg";
        case TRIANGLE:
            return (char*)":images/triangle.svg";
        case RECTANGLE:
            return (char*)":images/rectangle.svg";
        case VECTOR:
            return (char*)":images/vector.svg";
        case VECTOR2:
            return (char*)":images/vector2.svg";
        case TRANSPARENT:
            return (char*)":images/paper-transparent.svg";
        case BLACK:
            return (char*)":images/paper-black.svg";
        case WHITE:
            return (char*)":images/paper-white.svg";
        case PREVPAGE:
            return (char*)":images/go-page-previous.svg";
        case NEXTPAGE:
            return (char*)":images/go-page-next.svg";
        case BLANK:
            return (char*)":images/overlay-none.svg";
        case SQUARES:
            return (char*)":images/overlay-squares.svg";
        case LINES:
            return (char*)":images/overlay-lines.svg";
        case ISOMETRIC:
            return (char*)":images/overlay-isometric.svg";
        case MUSIC:
            return (char*)":images/overlay-music.svg";
        case CUSTOM:
            return (char*)":images/overlay-custom.svg";
        case OVERLAYSCALEUP:
            return (char*)":images/zoom-in.svg";
        case OVERLAYSCALEDOWN:
            return (char*)":images/zoom-out.svg";
        case OVERLAYROTATEUP:
            return (char*)":images/bg-rotate-plus.svg";
        case OVERLAYROTATEDOWN:
            return (char*)":images/bg-rotate-minus.svg";
        case CLEAR:
            return (char*)":images/clear.svg";
        case SELECTION:
            return (char*)":images/crop.svg";
        case NORMAL:
            return (char*)":images/line-normal.svg";
        case DOTLINE:
            return (char*)":images/line-dotline.svg";
        case LINELINE:
            return (char*)":images/line-lineline.svg";
        case COLORPICKER:
            return (char*)":images/color-picker.svg";
        case BACK:
            return (char*)":images/go-back.svg";
        case NEXT:
            return (char*)":images/go-next.svg";
        case CLOSE:
            return (char*)":images/close.svg";
        case SCREENSHOT:
            return (char*)":images/screenshot.svg";
        case CURSOR:
            return (char*)":images/cursor.svg";
        case MINIFY:
            return (char*)":images/screen.svg";
        case FULLSCREEN:
            return (char*)":images/fullscreen.svg";
        case FULLSCREEN_EXIT:
            return (char*)":images/fullscreen-exit.svg";
        case ROTATE:
            return (char*)":images/rotate.svg";
        case PAGEMENU:
            return (char*)":images/page-settings.svg";
        case UTILMENU:
            return (char*)":images/misc-settings.svg";
        case SAVE:
            return (char*)":images/save.svg";
        case OPEN:
            return (char*)":images/open.svg";
    }
    return (char*)"";
}